# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5d9c6829359a72a4251e17514299a19aea7eec8d03e96ba5d733fbb7c314fe04208a986928e54b2525ee8c821e4b1353ad93e825b166695163625f3964917c3

test:
  secret_key_base: eaad23ab36de5500a85846d32d3ef1e26d3c6aae9a1f2a6a27ffc15a4e2d65317648b854ec2e5fd472aeb46808a5fbb76b90957ccf343261ba64fbee072b42e6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
